services:
  backend:
    build: .
    environment:
      - DATABASE_URL=mysql://kniffel:kniffel@db/kniffel
    ports:
      - "8080:8080"
  db:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=kniffel
      - MARIADB_PASSWORD=kniffel
      - MARIADB_DATABASE=kniffel
    volumes:
      - ./data-mariadb:/var/lib/mysql      
